services:
    - type: web
    name: khilane-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
            - key: ADMIN_PASSWORD
        value: Bongumenzi1@
            - key: API_PASSWORD
        value: Bongumenzi1@
            - key: STAFF_PASSWORD
        value: Bongumenzi1@

    - type: web
    name: Khilane-Travel
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
            - type: rewrite
        source: /*
        destination: /index.html
