import React, { useState, useEffect } from "react";
import { Plane, Building2, Car, Bus, Check, X, Copy, ShieldCheck, Clock, Star, MapPin, Users } from "lucide-react";
type Tab = "flights" | "stays" | "cars" | "buses";
const NAVY = "#0A1931"; const GOLD = "#FFC300";
const mockFlights = [{id:1,airline:"FlySafair",code:"FA",logo:"FA",from:"JNB",to:"CPT",dep:"06:15",arr:"08:25",dur:"2h 10m",stops:"Direct",price:864,original:914,badge:true,seats:3},{id:2,airline:"Airlink",code:"4Z",logo:"4Z",from:"JNB",to:"CPT",dep:"08:40",arr:"10:55",dur:"2h 15m",stops:"Direct",price:902,original:952,badge:true,seats:5},{id:3,airline:"CemAir",code:"5Z",logo:"5Z",from:"JNB",to:"CPT",dep:"11:10",arr:"13:30",dur:"2h 20m",stops:"Direct",price:945,original:995,badge:false,seats:2},{id:4,airline:"LIFT",code:"GE",logo:"GE",from:"JNB",to:"CPT",dep:"14:05",arr:"16:20",dur:"2h 15m",stops:"Direct",price:989,original:1039,badge:false,seats:6},{id:5,airline:"FlySafair",code:"FA",logo:"FA",from:"JNB",to:"CPT",dep:"17:30",arr:"19:45",dur:"2h 15m",stops:"Direct",price:1025,original:1075,badge:true,seats:4},{id:6,airline:"Airlink",code:"4Z",logo:"4Z",from:"JNB",to:"CPT",dep:"19:15",arr:"21:30",dur:"2h 15m",stops:"Direct",price:1110,original:1160,badge:false,seats:1}];
const mockStays = [{id:101,name:"Beverly Hills Hotel Umhlanga",loc:"Umhlanga Rocks, Durban",rating:4.8,reviews:1243,price:2850,original:3200,per:"night",tag:"Beachfront",badge:true},{id:102,name:"The Oyster Box",loc:"Umhlanga Ridge",rating:4.9,reviews:892,price:3450,original:3800,per:"night",tag:"5-Star Luxury",badge:true},{id:103,name:"Sun City Resort",loc:"Rustenburg",rating:4.6,reviews:2104,price:1890,original:2100,per:"night",tag:"Family",badge:false},{id:104,name:"Cape Grace Fairmont",loc:"V&A Waterfront Cape Town",rating:4.9,reviews:756,price:4250,original:4600,per:"night",tag:"Harbour Views",badge:true}];
const mockCars = [{id:201,name:"Toyota Corolla Quest",type:"Sedan Manual",seats:5,company:"Avis",price:489,original:539,per:"day",badge:true},{id:202,name:"VW Polo Vivo",type:"Hatch Manual",seats:5,company:"Budget",price:425,original:475,per:"day",badge:true},{id:203,name:"Toyota Fortuner",type:"SUV Auto",seats:7,company:"Hertz",price:1150,original:1220,per:"day",badge:false}];
const mockBuses = [{id:301,company:"Intercape",from:"JNB Park",to:"CPT Station",dep:"18:00",arr:"12:30+1",dur:"18h30m",price:685,original:735,badge:true,type:"Sleepliner"},{id:302,company:"Greyhound",from:"Pretoria",to:"Durban",dep:"20:15",arr:"06:45+1",dur:"10h30m",price:520,original:570,badge:true,type:"Dreamliner"}];
export default function App(){
const [activeTab,setActiveTab]=useState("flights");const [searchFrom,setSearchFrom]=useState("JNB");const [searchTo,setSearchTo]=useState("CPT");const [departDate,setDepartDate]=useState("2026-10-15");const [returnDate,setReturnDate]=useState("");const [showResults,setShowResults]=useState(true);const [isSearching,setIsSearching]=useState(false);const [selected,setSelected]=useState(null);const [showModal,setShowModal]=useState(false);const [modalStep,setModalStep]=useState(1);const [bookingRef,setBookingRef]=useState("");const [docType,setDocType]=useState("sa");const [form,setForm]=useState({firstName:"",lastName:"",idNumber:"",passportNum:"",nationality:"South African",passportExpiry:"",email:"",phone:""});const [paymentMethod,setPaymentMethod]=useState("nedbank");const [copied,setCopied]=useState(false);
useEffect(()=>{setShowResults(true)},[]);
const handleSearch=()=>{setIsSearching(true);setShowResults(false);setTimeout(()=>{setIsSearching(false);setShowResults(true);document.getElementById("results")?.scrollIntoView({behavior:"smooth"})},900)};
const openBooking=(item)=>{setSelected(item);setModalStep(1);setShowModal(true);setBookingRef(`BK-2026-${Math.floor(1000+Math.random()*9000)}`)};
const nextStep=()=>{if(modalStep<4)setModalStep(s=>s+1)};const prevStep=()=>{if(modalStep>1)setModalStep(s=>s-1)};const closeModal=()=>{setShowModal(false);setModalStep(1)};
const copyBankDetails=()=>{navigator.clipboard?.writeText(`Nedbank - MG. Gwala - Acc: 1044602244 - Branch: 198765 - CA - Ref: ${bookingRef}`);setCopied(true);setTimeout(()=>setCopied(false),2000)};
const results = activeTab==="flights"?mockFlights:activeTab==="stays"?mockStays:activeTab==="cars"?mockCars:mockBuses;
return(<div className="min-h-screen bg-[#F6F7FB]" style={{fontFamily:"Inter,system-ui"}}>
<div className="w-full text-center py-2.5 text-[11px] sm:text-[13px] font-extrabold tracking-widest uppercase" style={{background:GOLD,color:NAVY}}>🇿🇦 TRAVEL PROUDLY SOUTH AFRICAN — SOUTH AFRICA'S LOWEST PRICES GUARANTEED 🇿🇦</div>
<header className="sticky top-0 z-30 backdrop-blur bg-white/85 border-b"><div className="mx-auto max-w-[1100px] px-4 h-[64px] flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-black" style={{background:NAVY}}>K</div><div><div className="font-black text-[18px]" style={{color:NAVY}}>Khilane Travel ✈️</div><div className="text-[11px] font-semibold text-emerald-600">ZAR Live v2.4 • R50 Beat • On-Site Booking • No Kiwi</div></div></div></div></header>
<main className="mx-auto max-w-[1100px] px-4 py-6">
<div className="grid lg:grid-cols-[1.15fr_0.85fr] gap-6">
<div className="rounded-[24px] bg-white shadow border overflow-hidden">
<div className="p-2 flex gap-1 bg-slate-50 m-2 rounded-full w-fit">{[{id:"flights",label:"Flights",icon:Plane},{id:"stays",label:"Stays",icon:Building2},{id:"cars",label:"Car Hire",icon:Car},{id:"buses",label:"Buses",icon:Bus}].map(t=>{const active=activeTab===t.id;return(<button key={t.id} onClick={()=>{setActiveTab(t.id);setShowResults(true)}} className={`h-9 px-4 rounded-full
